TypeError bei leerem Host abfangen
yakamara/redaxo_yrewrite pull request #460
Opened 2022-01-24 12:34 UTC by omphteliba

Wenn der Client keinen $host zurück liefert, taucht ein TypeError im syslog auf

Error: TypeError
Nachricht: Argument 1 passed to rex_yrewrite_path_resolver::resolveDomain() must be of the type string, null given, called in /var/www/html/factfinder/tld/de/htdocs/redaxo/src/addons/yrewrite/lib/yrewrite/path_resolver.php on line 45
Datei: redaxo/src/addons/yrewrite/lib/yrewrite/path_resolver.php
Zeile: 158

2022-06-15 08:13 UTC, alxndr-w commented
Wertvolle PRs wie dieser warten auf die Annahme. Kann ich behilflich sein? @dergel

2022-06-16 10:38 UTC, gharlan requested changes
Denke nicht, dass das die Lösung ist, die URL-Auflösung dann einfach als Ganzes abzubrechen.
Ich weiß allerdings noch nicht, wie man es stattdessen löst.

2022-06-16 12:03 UTC, alxndr-w commented
@gharlan das urspr. Problem, um das es geht, ist folgendes: Zeigt eine Domain am Webserver auf die REDAXO-Installation, die nicht in YRewrite vorhanden ist, entsteht ein Systemlog-Eintrag aufgrund eines Folgefehlers später im Code.

Dieser PR soll das unterbinden, indem abgebrochen wird, weil es diesen Host eben gar nicht gibt.

Korrekterweise würde man keine Domain auf den Serverpfad zeigen lassen.

Man könnte auch argumentieren, dass eine Domain, die nicht verzeichnet ist, im Frontend immer zu einem Ooops führen sollte, allerdings sehe ich dann schon unzählige Suppport-Anfragen in Slack.

2022-06-16 12:09 UTC, gharlan commented
> @gharlan das urspr. Problem, um das es geht, ist folgendes: Zeigt eine Domain am Webserver auf die REDAXO-Installation, die nicht in YRewrite vorhanden ist, entsteht ein Systemlog-Eintrag aufgrund eines Folgefehlers später im Code.

Ich denke nicht, dass das das Problem dieses PRs ist. Ich verstehe diesen PR so, dass es darum geht, wenn der Client keinen `Host: `-Header mitsendet. 

Der beschriebene TypeError kann bei deiner Konstellation eigentlich nicht auftreten. `rex_yrewrite::getHost()` würde da nicht `null` liefern.

2022-07-31 12:10 UTC, closed without merging