Readme Methode getTags() aktualisiert
yakamara/redaxo_yrewrite pull request #481
Opened 2022-06-20 05:29 UTC by TobiasKrais

die vorherigen Methoden sind deprecated

2022-06-20 05:30 UTC, TobiasKrais commented
Macht den PR https://github.com/yakamara/redaxo_yrewrite/pull/474 überflüssig.

2022-06-20 09:13 UTC, alxndr-w requested changes
Bitte englische README anpassen, bitte um Beispielcode-Ausgabe ergänzen, damit dem Entwickler klar wird, was man bekommt.

2022-06-20 09:54 UTC, alxndr-w requested changes
Es fehlen die Tags, wenn eine zweite Sprache online ist. Sorry für das Gemeckere, aber wenn, dann lass es uns gleich vollständig machen. 🤍

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<link rel="alternate" hreflang="en" href="https://beispiel.de/en/" />
```suggestion
<link rel="alternate" hreflang="en" href="https://example.org/en/" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta property="og:description" content="Redaxo Spielwiese zum Testen - Achtung toxisch!" />
```suggestion
<meta property="og:description" content="Der Text aus dem Beschreibungs-Feld" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta property="og:image" content="https://beispiel.de/media/yrewrite_seo_image/pic.jpg" />
```suggestion
<meta property="og:image" content="https://example org/media/yrewrite_seo_image/seo-image.jpg" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta property="og:url" href="https://beispiel.de/de/" />
```suggestion
<meta property="og:url" href="https://example.org/de/" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta name="twitter:title" content="Modultests / REDAXO Spielwiese" />
```suggestion
<meta name="twitter:title" content="Artikelname / Websitetitel" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta name="twitter:url" content="https://beispiel.de/de/" />
```suggestion
<meta name="twitter:url" content="https://example.org/de/" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta name="twitter:title" content="Modultests / REDAXO Spielwiese" />
```suggestion
<meta name="twitter:title" content="Artikelname / Websitetitel" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta name="twitter:title" content="Modultests / REDAXO Spielwiese" />
```suggestion
<meta name="twitter:title" content="Artikelname / Websitetitel" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta property="og:title" content="Modultests / REDAXO Spielwiese" />
```suggestion
<meta property="og:title" content="Artikelname / Websitetitel" />
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<meta name="description" content="Redaxo Spielwiese zum Testen - Achtung toxisch!">
```suggestion
<meta name="description" content="Der Text aus dem Beschreibungs-Feld">
```

2022-06-20 09:54 UTC, alxndr-w commented on README.md
> +<link rel="canonical" href="https://beispiel.de/de/" />
```suggestion
<link rel="canonical" href="https://example.org/de/" />
```

2022-06-20 09:56 UTC, alxndr-w commented
Ach, sehe, die Sprachen-Tags sind doch dabei. Bin am Smartphone, da habe ich den Überblick verloren.

2022-06-20 10:36 UTC, TobiasKrais commented
Ah, jetzt blick ichs! Ja, alles gut. Kein Problem. Sehe ich auch so wie du. Hab alles angepasst. Kannst gerne nochmals drüber schauen.

2022-06-20 10:40 UTC, alxndr-w commented on README.md
> +```
```suggestion
```html
```

2022-06-20 10:40 UTC, alxndr-w commented on README.md
>  ```
```suggestion
```php
```

2022-06-20 10:41 UTC, TobiasKrais commented on README.md
>  ```
Das ist ja schick. Danke! Wieder was gelernt.

2022-06-20 10:41 UTC, alxndr-w approved these changes
Daumen hoch! 

/cc @tbaddade

2022-06-20 15:49 UTC, gharlan commented
Kannst du das noch in die englische Readme übernehmen?

2022-06-23 20:32 UTC, gharlan commented
@TobiasKrais Kannst du hier noch `twitter:image` ergänzen?

2022-06-24 07:00 UTC, TobiasKrais commented
Ja gerne. Sehr aufmerksam. Das habe ich nachträglich hinzugefügt und vergessen in diesem PR nachzuziehen. Ist erledigt.

2022-06-24 07:31 UTC, tbaddade commented
Ich finde noch ein Hinweis auf den EP gut. Ggf. sogar mit einem Code-Beispiel wie man die Tags anpassen könnte.

2022-06-24 07:43 UTC, TobiasKrais commented
Finde ich eine gute Idee. Hast du ein Beispiel parat? Oder kannst du dafür sogar einen PR machen?

2022-06-24 07:46 UTC, tbaddade commented
> Oder kannst du dafür sogar einen PR machen?

Mache ich gern.

2022-06-24 08:09 UTC, merged

2022-06-24 08:22 UTC, tbaddade commented
@TobiasKrais https://github.com/yakamara/redaxo_yrewrite/pull/485