Beispiel für EP YREWRITE_SEO_TAGS
yakamara/redaxo_yrewrite pull request #485
Opened 2022-06-24 08:21 UTC by tbaddade

2022-06-28 07:54 UTC, gharlan requested changes

2022-06-28 07:54 UTC, gharlan commented on README.md
> +\rex_extension::register('YREWRITE_SEO_TAGS', function(\rex_extension_point $ep) {
```suggestion
rex_extension::register('YREWRITE_SEO_TAGS', function(rex_extension_point $ep) {
```

Ich würde in der Doku beim einheitlichen Schema bleiben. Und da REDAXO bisher selbst keine Namespaces nutzt, auch hier ohne Backslashes.

2022-06-28 07:54 UTC, gharlan commented on README.md
> +    $tagsTwitter['twitter:title'] = '<meta name="twitter:title" content="'.$title.'" />';
Der Code scheint mir nichts zu passen, aus dem EP bekommt man nur ein Array (`$tags`), die verschiedenen Tags sind da bereits gemerged.

2022-06-28 09:27 UTC, tbaddade commented on README.md
> +    $tagsTwitter['twitter:title'] = '<meta name="twitter:title" content="'.$title.'" />';
> Der Code scheint mir nichts zu passen, aus dem EP bekommt man nur ein Array ($tags), die verschiedenen Tags sind da bereits gemerged

Der Key bleibt erhalten, sodass man darüber die Tags entsprechend anpassen/ersetzen kann.

2022-06-28 09:37 UTC, gharlan commented on README.md
> +    $tagsTwitter['twitter:title'] = '<meta name="twitter:title" content="'.$title.'" />';
Ja, aber du nutzt die falschen Variablen. Es muss überall `$tags` sein.

2022-06-30 06:57 UTC, gharlan approved these changes

2022-06-30 06:57 UTC, merged